-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "macOS")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            passes = 2,
            size = 2,
        },
        rounding = 7,
        rounding_power = 6.0,
        shadow = {
            range = 10,
            render_power = 4,
        },
    },
    general = {
        col = {
            active_border = "0xff5e5c64",
        },
        gaps_out = 6,
        resize_on_border = true,
    },
})
