-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            passes = 2,
            size = 2,
        },
        rounding_power = 2.0,
        shadow = {
            range = 10,
            render_power = 4,
        },
    },
    general = {
        col = {
            active_border = "0xff5e5c64",
        },
        gaps_out = 4,
        resize_on_border = true,
    },
})
