vim.pack.add({
  "https://github.com/mason-org/mason.nvim",
  "https://github.com/mason-org/mason-lspconfig.nvim",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/nvim-tree/nvim-web-devicons",
  "https://github.com/nvim-lualine/lualine.nvim",
  "https://github.com/akinsho/bufferline.nvim",
  "https://github.com/stevearc/oil.nvim",
  "https://github.com/dmtrKovalenko/fff",
  "https://github.com/folke/tokyonight.nvim",
  "https://github.com/rebelot/kanagawa.nvim",
  "https://github.com/saghen/blink.lib",
  "https://github.com/saghen/blink.cmp",
  "https://github.com/xiyaowong/transparent.nvim",
  "https://github.com/nvim-mini/mini.surround",
  "https://github.com/nvim-mini/mini.pairs",
  "https://github.com/nvim-mini/mini.starter",
  "https://github.com/scottmckendry/cyberdream.nvim",
  "https://github.com/folke/snacks.nvim",
})

require("plugins.oil")
require("plugins.fff")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.blink-cmp")
require("plugins.lsp.lsp-config")
require("plugins.lsp.mason")
require("plugins.transparent")
require("plugins.mini")
require("plugins.snacks")
